In [2]:
import numpy as np

In [15]:
# create array from list
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape,arr.itemsize)
print(arr.ndim)
arr2=np.array([1,2,3,4,5,"prime"]) #create string array
print(arr2,type(arr2),arr2.dtype,arr2.shape)

arr2D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,4,6]]])
print(arr2D[0,1,1],arr2D.size)


[1 2 3 4 5] <class 'numpy.ndarray'> (5,) 8
1
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
5 12


In [48]:
#create
arr1=np.zeros((2,3),dtype="int64")#prefil
print(arr1,arr1.shape)

arr2=np.ones((2,3),dtype="int64") #prefill
print(arr2,arr2.shape)

arr3=np.full((3,4),100)
print(arr3,arr3.shape)

arr4=np.eye((3)) #identity matrix - diagonal value 1 all other values 0
print(arr4,arr4.shape)

arr5=np.arange(0,11,2) #range elements
print(arr5,arr5.shape)

arr6=np.linspace(1,100,3) #evenly spaced arrays
print(arr6,arr6.shape)

arr7=np.diag([10,20,30])
print(arr7)

arr8=np.random.rand(4)
print(arr8)

arr9=np.random.randint(1,20,5)
print(arr9)








[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)
[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]
[0.65281956 0.68001316 0.49332383 0.96285649]
[ 1  7 10 16 13]


In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr=arr.astype(np.float64)
print(float_arr)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [75]:
#operations on array
#reshaping
arr9=np.array([[1,2,3],[4,5,6]])
print(arr9,arr9.shape)

reshaped=arr9.reshape((3,2))
print(reshaped,reshaped.shape)


print(arr9.resize((3,2)))
new_arr=arr9.swapaxes(0,1)
print(new_arr)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
None
[[1 3 5]
 [2 4 6]]


In [23]:
flattend=arr.flatten()
print(flattend,flattend.shape)

[1 2 3 4 5 6 7 8 9] (9,)


In [32]:
arr10=np.array([1,3,4,6]) #facny indexing
idx=[2,3]
print(arr10[idx])

[4 6]


In [35]:
arr=np.array([1,2,3,4]) #BOOLEAN INDEXING
print(arr[arr>2])
print(arr[arr % 2 ==0])

[3 4]
[2 4]


In [39]:
#slicing
arr=np.array([2,6,3,4])
print(arr[1:3])
print(arr[1:])
print(arr[:3])
print(arr[::2])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

[3 3]
[3 3 4]
[2 3 3]
[2 3]


In [44]:
#copy vs view
lists=[1,2,3,4,5]
sub_list=lists[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(lists)
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3]
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)

#if we want to create copy in numpy we use .copy
arr2=np.array([1,2,3,4,5])
sub_arr2=arr2[1:3].copy()
sub_arr2[0]=200
print(arr2)



[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]
[1 2 3 4 5]


In [50]:
#comparison operator
arr=np.array([2,3,5])
print(arr>3)

[False False  True]


In [65]:
arr=np.array([2,3,4])
print(sum(arr))
print(np.median(arr))
print(np.mean(arr))
print(np.sqrt(arr))
print(np.exp(arr))
arr3=[2.5,3.3,5]
print(np.round(arr3))

9
3.0
3.0
[1.41421356 1.73205081 2.        ]
[ 7.3890561  20.08553692 54.59815003]
[2. 3. 5.]


In [77]:
#random number
#rand -between 0 and 1
random_num=np.random.rand(5)
print(random_num)

[0.88827076 0.26467738 0.24017514 0.04901472 0.42810504]


In [78]:
random_2d=np.random.rand(2,3)
print(random_2d)

[[0.10795536 0.64078807 0.90044028]
 [0.21818948 0.05041258 0.07231614]]


In [85]:
#randn - real numbers (mean~0)
random_num_randn=np.random.randn(5)
print(random_num_randn)

[-0.90561048 -0.89808938  0.45187984 -0.85947418 -0.53479453]


In [84]:
#randint- generates number 
random_randint=np.random.randint(1,10)
print(random_randint)
random2=np.random.randint(1,10,5)
print(random2)

5
[1 2 1 2 9]


In [82]:
#choice
colors=["red","green","yellow"]
print(np.random.choice(colors))

green


In [86]:
np.random.seed(10)
print(np.random.randint(1,100))

10


In [90]:
#shuffle
arr=np.array([2,3,1,4])
new_arr=np.random.permutation(arr)
print(new_arr)

[4 1 3 2]


In [93]:
#newaxis
arr=np.array([2,4,5,6])
new_arr=arr[:,np.newaxis]
print(new_arr)

[[2]
 [4]
 [5]
 [6]]


In [94]:
a=np.array([2,4,5])
for x in a:
    print(x)

2
4
5


In [97]:
b=np.array([[2,3,4],[5,6,7]])
for row in b:
    for element in row:
        print(element)

2
3
4
5
6
7


In [106]:
a = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],

    [
        [7,8,9],
        [10,11,12]
    ]
])

# # for block in a:
# #     for row in block:
# #         for element in row:
# #          print(element)

# for x in np.nditer(a):
    # print(x)

for index,value in np.ndenumerate(a):
    print(index,value)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [113]:
#searching
#where
a=np.array([20,30,43,50])
index=np.where(a%2==0)
print(index)
print(np.argmax(a))
#nonzero
b=np.array([0,23,200,0])
print(np.nonzero(b))
result=np.where(a>=40,"pass","fail")
print(result)
#searchsorted
print(np.searchsorted(a,25)) #returnd index of palce where we can place 25 so array will remain sorted

(array([0, 1, 3]),)
3
(array([1, 2]),)
['fail' 'fail' 'pass' 'pass']
1


In [118]:
#boolean filtering
a=np.array([[20,30],[40,50]])
print(a[a>25])

#multiple condition 
print(a[(a>25) & (a<40)])

[30 40 50]
[30]


In [3]:
a=np.array([20,10,40,30])
print(np.sort(a))
b=np.array([[20,80],[40,50]])
print(np.sort(b))
print(np.sort(b,axis=0)) #column wise
print(np.sort(b,axis=1)) #row wise
#descending sorting use ::-1
print(np.sort(a)[::-1])

arr=np.array([10,50,40,20])
print(np.argsort(arr)) # returns indices that can be used to sort

[10 20 30 40]
[[20 80]
 [40 50]]
[[20 50]
 [40 80]]
[[20 80]
 [40 50]]
[40 30 20 10]
[0 3 2 1]


In [129]:
#id
a=np.array([1,2])
b=a.view()
print(id(a))
print(id(b))

2053665392656
2053665393904


In [134]:
# joining arrays
arr=np.array([
    [2,3],
    [4,5]
])
arr2=np.array([[1,5],
               [7,8]])

print(np.concatenate((arr,arr2)))
print(np.concatenate((arr,arr2),axis=0)) #rows increases
print(np.concatenate((arr,arr2),axis=1)) #column increases


[[2 3]
 [4 5]
 [1 5]
 [7 8]]
[[2 3]
 [4 5]
 [1 5]
 [7 8]]
[[2 3 1 5]
 [4 5 7 8]]


In [146]:
arr=np.array([10,20,30])
arr2=np.array([40,50,60])
# print(np.concatenate((arr,arr2),axis=1)) #give error axis not found
#stack
print(np.stack((arr,arr2),axis=1)) #creates new axis
print(np.hstack((arr,arr2))) # joins array horizontaly
print(np.vstack((arr,arr2))) # joins array vertically (by default)
print(np.dstack((arr,arr2))) #creates a 3rd axis used in image processing

[[10 40]
 [20 50]
 [30 60]]
[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]
[[[10 40]
  [20 50]
  [30 60]]]


In [154]:
#splitting arrays np.split()
arr=np.array([2,3,4,5,6,7])
result=np.split(arr,2)
print(result)

result2=np.split(arr,[1,4])# instead of spliting in equal parts split it from specific indices
print(result2)

[array([2, 3, 4]), array([5, 6, 7])]
[array([2]), array([3, 4, 5]), array([6, 7])]


In [151]:
#np.array_split - improved version of split ,split into unequal parts if equal elements not available
arr=np.array([4,5,6])
result=np.array_split(arr,2)
print(result)



[array([4, 5]), array([6])]


In [157]:
#splitting in 2d array
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
result=np.split(arr,2) #row wise splitting
print(result)

result2=np.split(arr,2,axis=1) #column wise splitting
print(result2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [169]:
#h-split equal to (arr,2,axis=1)
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
result=np.hsplit(arr,2)
print(result)

#v-split equal to axis=0
result2=np.vsplit(arr,2)
print(result2)

#dsplit -depth wise split
arr2=np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])
result3=np.dsplit(arr2,3)
print(result3)


[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]]])]


In [170]:
#real life example
marks=np.array([2,5,3,6,7,8])
class1,class2 = np.split(marks,2)
print(class1)
print(class2)

[2 5 3]
[6 7 8]


In [174]:
#as it split in from of list so
num=np.array([2,3,4,5,6,7])
parts=np.array_split(num,3)
print(parts[0])
print(parts[1])
print(parts[2])

[2 3]
[4 5]
[6 7]


In [4]:
import pandas as pd

df = pd.DataFrame({
    "A":[1,2,3],
    "B":[4,5,6]
})

print(df.iloc[1,0])

2


In [5]:
df = pd.DataFrame({
    "A":[10,20,30],
    "B":[40,50,60]
})

print(df.loc[1,"B"])

50


In [6]:
import pandas as pd

s=pd.Series([10,20,None])

print(s.count())

2


In [7]:
import pandas as pd

s=pd.Series([10,20,None])

print(s.size)

3
