In [10]:
import pandas as pd
import numpy as np

In [2]:
print(pd.__version__)

2.3.3


In [6]:
#from list
s=pd.Series([1,2,3,4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [8]:
#custom index
s=pd.Series(
    [1,2,3,4],
     index=["A","B","C","D"]
)
print(s)

A    1
B    2
C    3
D    4
dtype: int64


In [9]:
#from tuples
s=pd.Series((2,3,4))
print(s)

0    2
1    3
2    4
dtype: int64


In [11]:
#from numpy_array
arr=np.array([1,2,3,4])
print(arr)
s=pd.Series(arr)
print(s)

[1 2 3 4]
0    1
1    2
2    3
3    4
dtype: int64


In [12]:
#from dictionary - make keys as index
student = {
    "riya":90,
    "shreya":99,
    "kashi":87
}

s=pd.Series(student)
print(s)

riya      90
shreya    99
kashi     87
dtype: int64


In [14]:
#from scalar values
s=pd.Series(100)
print(s)
#if you want multiple
s=pd.Series(100,
           index=["A","B","C","D"])
print(s)

0    100
dtype: int64
A    100
B    100
C    100
D    100
dtype: int64


In [46]:
#attribute in series
s=pd.Series([1,2,3,4,5],
            index=["A","B","C","D","E"],
            name="Numbers"
             )
# print(s)
print(s.values) #values - return values of only
print(type(s.values)) #type of values
print(s.index) #returns only index 
print(s.dtype) #returns only datatype of series
print(s.shape) # returns dimension -series in 1D so shape contain one value
print(s.size) # returns number of element
print(s.ndim) # returns number of dimension
print(s.name) # returns series name
print(s.empty) # returns true oe false check whether series is empty or not

#accessing elements in series
print(s["A"]) #acces by label
# print(s[0])  # acces by position 
#use loc label based indexing safer
print(s.loc["C"]) # uses custom index 
print(s.iloc[2]) #uses integer position
print(s.iloc[[2,3]]) #uses integer position
#slicing - same as numpy
print(s.iloc[0:4])
print(s.loc["B":"D"]) #D - included
#updating
s.loc["A"]=300
print(s) 
#adding element
s["F"]=400
print(s)
#delete and returns a new series by default
s=s.drop("C")
print(s)
#checking if index exist
print("A" in s)
#boolean filtering
print(s[s>2])
print(s)
print( 300 in s.values)
print("A" in s.index)






[1 2 3 4 5]
<class 'numpy.ndarray'>
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
int64
(5,)
5
1
Numbers
False
1
3
3
C    3
D    4
Name: Numbers, dtype: int64
A    1
B    2
C    3
D    4
Name: Numbers, dtype: int64
B    2
C    3
D    4
Name: Numbers, dtype: int64
A    300
B      2
C      3
D      4
E      5
Name: Numbers, dtype: int64
A    300
B      2
C      3
D      4
E      5
F    400
Name: Numbers, dtype: int64
A    300
B      2
D      4
E      5
F    400
Name: Numbers, dtype: int64
True
A    300
D      4
E      5
F    400
Name: Numbers, dtype: int64
A    300
B      2
D      4
E      5
F    400
Name: Numbers, dtype: int64
True
True
A    600
B      4
D      8
E     10
F    800
Name: Numbers, dtype: int64


In [51]:
#arithemetic 
s1=pd.Series([1,2,3], index=["A","B","C"])
s2=pd.Series([4,5,6], index=["A","B","G"])
print(s1+s2) # aligns data by index labels
print(s1>4)
#boolean filtering
print(s1[(s1>1) & (s1<3)])


A    5.0
B    7.0
C    NaN
G    NaN
dtype: float64
A    False
B    False
C    False
dtype: bool
B    2
dtype: int64


In [58]:
#stastical functions
marks=pd.Series([1,2,3,4,5,5])
print(marks.sum())
print(marks.mean())
 
print(marks.mean())
print(marks.mode())
print(marks.median())
print(marks.std())
print(marks.var())
print(marks.unique())
print(marks.nunique()) #returns the number of unique values
print(marks.value_counts()) # return frequency count of each value
print(marks)

20
3.3333333333333335
3.3333333333333335
0    5
dtype: int64
3.5
1.632993161855452
2.666666666666667
[1 2 3 4 5]
5
5    2
1    1
2    1
3    1
4    1
Name: count, dtype: int64
0    1
1    2
2    3
3    4
4    5
5    5
dtype: int64


In [65]:
s=pd.Series([1,0,3], index=["D","B","C"])
print(s)
print(s.sort_values()) # sorting with values
print(s.sort_values(ascending=False)) #sorting in descending order
print(s.sort_index()) #sorting in index
print(s.astype(float))
print(s.apply(str)) #let you apply function to every element


D    1
B    0
C    3
dtype: int64
B    0
D    1
C    3
dtype: int64
C    3
D    1
B    0
dtype: int64
B    0
C    3
D    1
dtype: int64
D    1.0
B    0.0
C    3.0
dtype: float64
D    1
B    0
C    3
dtype: object


In [71]:
marks=pd.Series([1,np.nan,3,np.nan,5,5])
print(marks)
print(marks.isna())
print(marks.isnull())
print(marks.notna())
print(marks.dropna())
print(marks.fillna(8))

0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
5    5.0
dtype: float64
0    False
1     True
2    False
3     True
4    False
5    False
dtype: bool
0    False
1     True
2    False
3     True
4    False
5    False
dtype: bool
0     True
1    False
2     True
3    False
4     True
5     True
dtype: bool
0    1.0
2    3.0
4    5.0
5    5.0
dtype: float64
0    1.0
1    8.0
2    3.0
3    8.0
4    5.0
5    5.0
dtype: float64
