# 

In [9]:
import numpy as np
num=np.arange(1,21)
print(num)
arr=np.zeros((3,4))
print(arr)
identity_matrix=np.eye((4))
print(identity_matrix)
arr3=np.linspace(5,50,10)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [10]:
arr4=np.random.randint(10,100,(3,3))
print(arr4)

[[32 25 72]
 [91 16 28]
 [55 77 71]]


In [12]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr.shape,arr.size,arr.dtype)

(2, 3) 6 int64


In [14]:
arr5=np.array([1,2,3,4])
arr6=arr5.astype(np.float64)
print(arr6)

[1. 2. 3. 4.]


In [18]:
arr7=np.array(range(50,101,5))
print(arr7)

[ 50  55  60  65  70  75  80  85  90  95 100]


In [21]:
arr8=np.arange(2,101,2)
print(arr8)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [30]:
arr=np.arange(1,26).reshape(5,5)
print(arr)
print(arr[2,2])
print(arr[4])
print(arr[:,2])
print(arr[1:4,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
13
[21 22 23 24 25]
[ 3  8 13 18 23]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [32]:
arr=np.arange(20)
print(arr)
print(arr[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [50]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print(arr[1])
print(arr[:,3])
new_arr=np.where(arr%2==0,0,arr)
print(new_arr)
new_Arr2=np.where(arr>50,-1,arr)
print(new_Arr2)
arr[[0,-1]]=arr[[-1,0]]
print(arr)
arr[:,[0,-1]]=arr[:,[-1,0]]
print(arr)
# arr[arr%2==0]=0
# print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[5 6 7 8]
[ 4  8 12 16]
[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[13 14 15 16]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]
[[16 14 15 13]
 [ 8  6  7  5]
 [12 10 11  9]
 [ 4  2  3  1]]


In [60]:
arr=np.array([12,15,18,20,25])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.max(arr),",",np.argmax(arr))
print(arr**2)
print(np.where(arr%2==0,arr**3,arr))
print(np.cumsum(arr))
print(np.cumprod(arr))


90
18.0
18.0
4.427188724235731
19.6
25 , 4
[144 225 324 400 625]
[1728   15 5832 8000   25]
[12 27 45 65 90]
[     12     180    3240   64800 1620000]


In [61]:
numbers=np.arange(2,101)
is_prime=np.ones(len(numbers),dtype=bool)
for i in range(2,int(np.sqrt(100))+1):
    is_prime[(numbers%i==0) & (numbers!=i)] = False

primes=numbers[is_prime]
print(primes)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


In [63]:
arr=np.array([2,2,43,5,6,7,2,2])
# print(np.unique(arr))
values,count=np.unique(arr,return_counts=True)
print(values)
print(count)

[ 2  5  6  7 43]
[4 1 1 1 1]


In [70]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
new_Arr=arr.flatten()
print(new_Arr)
print(arr.ravel())


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [73]:
arr=np.arange(1,21).reshape(5,4)
print(arr)
print(arr.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


In [76]:
arr=np.arange(24).reshape(2,3,4)
print(arr)
new_Arr=np.swapaxes(arr,1,2)
print("\n\n")
print(new_Arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [77]:
arr = np.array([10,20,30,40])

print(arr.shape)


(4,)


In [80]:
row=arr[np.newaxis,:]
print(row)
print(row.shape)
new_arr=np.squeeze(row)
print(new_arr)
print(new_arr.shape)


[[10 20 30 40]]
(1, 4)
[10 20 30 40]
(4,)


In [84]:
arr=np.array([1,2,3])
new_arr=np.broadcast_to(arr,(4,3))
print(new_arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [85]:
arr=np.array([[1],[2],[3]])
arr2=np.array([[10,20,30]])
print(arr+arr2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [87]:
arr=np.array([1,2,3,4,56,7,8,9])
index=np.where(arr==9)
print(index)
print(np.sort(arr))


(array([7]),)
[ 1  2  3  4  7  8  9 56]


In [104]:
arr=np.array([[5,2,4],[9,6,2]])
# print(np.sort(arr)) #row wise sort
#print(np.sort(arr,axis=0))# column wise sort
print(np.sort(arr,axis=None).reshape(arr.shape))
print("")
print(arr[arr>2])
print(arr[arr%2==0])
mean=np.mean((arr))
print(mean)
print(arr[arr>mean])

      

[[2 2 4]
 [5 6 9]]

[5 4 9 6]
[2 4 6 2]
4.666666666666667
[5 9 6]


In [106]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.concatenate((A,B)))

[1 2 3 4 5 6]


In [108]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[ 12,13,14],
            [15,26,28]])
print(np.hstack((A,B)))
print(np.vstack((A,B)))

[[ 1  2  3 12 13 14]
 [ 4  5  6 15 26 28]]
[[ 1  2  3]
 [ 4  5  6]
 [12 13 14]
 [15 26 28]]


In [109]:
arr=np.arange(1,21)
print(np.split(arr,4))


[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20])]


In [110]:
arr=np.arange(1,14)
print(np.array_split(arr,3))

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9]), array([10, 11, 12, 13])]


In [113]:
arr=np.random.random(10)
print(arr)

[0.06667203 0.11372865 0.17698007 0.93436427 0.31645477 0.55490377
 0.37632594 0.32098708 0.1035519  0.12863454]


In [118]:
arr=np.random.randint(1,100,size=(5,5))
print(arr)

[[45 18  6 56 23]
 [51 37 46 75 24]
 [42 20  7 30 89]
 [62  9 14  8 47]
 [42 43 78 99 80]]


In [123]:
np.random.seed(3)
print(np.random.randint(1,5,(5,5)))

[[3 1 2 4 1]
 [1 1 2 2 4]
 [3 4 2 2 3]
 [2 4 3 1 1]
 [1 2 4 3 1]]


In [130]:
arr=np.array(["red","green","blue"])
new_Arr=np.random.choice(arr,size=1)
print(new_Arr)

['red']


In [143]:
arr1=np.arange(1,7).reshape(2,3)
arr2=np.arange(1,7).reshape(3,2)
arr3=np.matmul(arr1,arr2)
print(arr3)
print(arr1@arr2)
arr4=np.arange(1,5).reshape(2,2)
print(np.linalg.det(arr4))
arr4_inv=np.linalg.inv(arr4)

print(np.linalg.trace(arr4))
print(np.linalg.matrix_rank(arr4))
values,vectors=np.linalg.eig(arr4)
print(values)
print(vectors)
print(np.matmul(arr4,arr4_inv))

[[22 28]
 [49 64]]
[[22 28]
 [49 64]]
-2.0000000000000004
5
2
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [150]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr)
rotated=np.rot90(arr,k=-1)
# print(rotated)
rotated2=np.rot90(arr,k=2)
# print(rotated2)
rotated3=np.rot90(arr,k=3)
print (rotated3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [153]:
arr=np.array([2,4,2,4,5,6,7,8])
unique,counts=np.unique(arr,return_counts=True)
result=unique[np.argsort(counts)]
print(result)
duplicate=unique[counts>1]
print(duplicate)

[6 5 8 7 2 4]
[2 4]


In [156]:
#second largest element
arr=np.array([2,4,2,4,5,6,7,8])
second_largest=np.unique(arr)[-2]
print(second_largest)
top3=np.sort(np.partition(arr,-3))[-3:]
print(top3)

7
[6 7 8]
